### PR TITLE
feat: support bundling of css `@import` rules

### PR DESCRIPTION
**Pull request by nobkd**
Support bundling of `@import` rules, useful, e.g. when importing CSS from `node_modules`

### TODO:

- [x] Write a simple test that involves `@import`

### CODE REVIEW

**Comment by tipiirai** [comment]
Seems like a legit feature. One thing to note that hot-reloading is not supported for @import:ed files since Nue has no way of tracking those dependencies (without writing a Lightning CSS extension, but that feels like an overkill)

**Comment by nobkd** [comment]
~~The test for Windows seems to fail, because of the code on master.
Here is the same run, but just for the branch (I reset to before the last merge commit, to be able to test without jest issues): https://github.com/nobkd/nue/actions/runs/9293144796~~

The thing about not being able to trace `@import`ed files for hot reloading should probably be mentioned in the docs then. This also probably only occurs, when the CSS file is in a local project, and not from a package... I agree, that it would be hard to track changes for imported files, and probably isn't needed.
We can still think about the possibility of being able to modify the lightningcss config that is passed to the transformation/bundling (#220)

**Comment by nobkd** [comment]
@tipiirai (off-topic)

> [!important]
> It seems like you haven't got any pings for the `create-nue` repo for a long time.
> Please also look at the pull requests there, when you read this. :)
> 
> This nuejs/create-nue#43 blocks Windows usage.
> Same goes for `nuekit` (see #179 and #253 fixed with #239 and #268) because there was no release in a long time.

> [!Important]
> This should only get merged after #285 is merged somewhere (means, the tests are working!)

**Comment by tipiirai** [comment]
@import sounds like the right solution to include Glow styling from node_modules, instead of hacking the dependency inside nuekit

**Comment by nobkd** [comment]
> `@import` sounds like the right solution to include Glow styling from node_modules, instead of hacking the dependency inside nuekit

I'm not sure, how exactly you mean that :shrug:

But just, so you know: Imports from `node_modules` have to provide the path to/with `node_modules` (relative or absolute), it is not resolved automatically by lightningcss.

So I don't know how exactly you would do that when `glow` is just installed (globally) because of `nuekit` or locally, because `nuekit` is local, so...

**Comment by tipiirai** [comment]
So the syntax of importing from node_modules is something like this ?

``` css
@import url("node_modules/nuekit/browser/syntax.css")
```

And the imported CSS is always bundled inside the parent CSS regardless of where it is imported?

The above would allow me to get rid of the automagical syntax.css auto-inclusion:

https://github.com/nuejs/nue/blob/master/packages/nuekit/src/site.js#L279

Thanks!

**Comment by nobkd** [comment]
I'm not sure. Probably. It's too long in the past that I did the code changes. Also I not completely sure, what exactly you want to do. 

You probably can use the resolvePath from init.js to get an absolute path to the css.
But what's next? 

---

~~BTW: I forgot to change the merge request branch to point to master. So the changes from here are on dev now, but not on master.~~ (edit: merged dev to master)

**Pull request merged**
