### PR TITLE
Fix all tests with `bun test`

### PR DESCRIPTION
**Pull request by fritx**
Before fix:
image

After fix:
image

Steps to reproduce:
```sh
cd nuejs/nue
bun install
bun test
```

Description:
1. Replace `..` with `../index.js` in `compile.test` and `render.test`, ref: https://github.com/nuejs/nue/commit/4e77356cbc487be8af2a55081e3a001b7dfef02f#r135937470
1. `write()` is async and should be awaited
1. [bun] `workspace` should be `packages/*` (consistent with pnpm-workspace.yaml), otherwise `bun/npm install` will not install dependencies of nuekit
1. [bun] `esbuild` is required while `bun test` and should be added to `nuekit/devDependencies`
1. [bun] bun.lockb changed (we can git-diff via some configs, ref: https://bun.sh/docs/install/lockfile)

### CODE REVIEW

**Comment by nobkd** [comment]
https://github.com/nuejs/nue/blob/854f20f53aecd8f32d87860b760cd24b8f1a3209/packages/nuejs/test/compile.js#L2

This line above also uses `..`-import. It's probably better to be consistent and use `../index.js` everywhere. (Even if nothing fails with the current)
What do you think?

**Comment by fritx** [comment]
> This line above also uses `..`-import. It's probably better to be consistent and use `../index.js` everywhere. (Even if nothing fails with the current) What do you think?

Excellent! I'm agreed. Just pushed again. @nobkd

**Comment by tipiirai** [comment]
Super cool. Thank you

**Comment by tipiirai** [comment]
Thanks. I am so happy to get these important fixes/additions.

**Comment by tipiirai** [comment]
@fritx I was thinking of not introducing esbuild as a devDependency, because it's such a big package. Maybe have the test 
 task load esbuild asynchronously and if found, only then run the test. What do you think?

**Comment by fritx** [comment]
@tipiirai my pleasure. Yes, I was considering it hard too.

I ended up with requiring esbuild in devDeps and the testing, because I found it already in pnpm-lock.yaml: 
https://github.com/nuejs/nue/blob/master/pnpm-lock.yaml#L31-L34

> Maybe have the test
task load esbuild asynchronously and if found, only then run the test.

IMO, in principle, we should test all the features that the library supports. But we should still try a better way to remove it from `devDeps` (to keep simplicity).

Maybe move it to `optionalDeps` and ~~find a way to manually turn it on in CI testing~~ ( [it's already there](https://github.com/nuejs/nue/blob/master/packages/nuekit/test/kit.test.js#L236) ) ?

**Pull request merged**
