### PR TITLE
Update custom-layouts.md

### PR DESCRIPTION
**Pull request by seneca**
In the picture above the blue box containing aside, page head, page foot and beside is not named. Shouldn't it be named main?

### CODE REVIEW

**Comment by nobkd** [comment]
If you mean this image, I agree, that the main area should be named `main` (or with the slot name? See https://github.com/nuejs/nue/issues/369#issuecomment-2370652249)


from here: https://nuejs.org/docs/custom-layouts.html

**Comment by tomByrer** [comment]
@nobkd is the right hand side label `beside` a typo?
Seems it also should be `aside`, or maybe `aside @complementary`?
https://github.com/nuejs/nue/blob/master/packages/nuejs.org/docs/layout.html#L16

**Comment by nobkd** [comment]
No, iirc it isn't. All bold values are html `elements` (with slot I think), all non-bold ones are `@name="<component>"` layout components, you can define in your layout component files (maybe it can even be a non-layout component, but I'm not sure, as I haven't tested that one)
For the components, you can decide, what the html element is, yourself

You can see an usage example for pagefoot in #373

**Comment by tipiirai** [comment]
I'm doing a significant update to the documentation. Make it much clearer and the product should feel much less "magical". Here is a new picture for this specific topic I'm going to use

**Comment by nobkd** [comment]
Wasn't `<footer>` something different from `@name="pagefoot"`?
Imo it makes sense to have a footer element at the bottom of the page, not inside the main at all, but e.g. where you put `@bottom` in your graphic. Maybe even just replacing it.
I'd have to recheck how it is semantically, where you put the footer element, but I always thought, you should use one footer, at the end of the page, not inside main

**Pull request closed without merging**
