### PR TITLE
refactor: nue.js

### PR DESCRIPTION
**Pull request by Simon-He95**

### CODE REVIEW

**Comment by tipiirai** [comment]
Thanks for the heads up. However, the strict equality comparisons are against Nue's [formatting/type conversion rules](https://github.com/nuejs/nuejs/blob/master/CONTRIBUTING.md#formatting-rules).

**Comment by Simon-He95** [comment]
> Thanks for the heads up

OK, I've undone the changes to the strict equality comparisons

**Comment by tipiirai** [comment]
Thanks! Can you clarify a bit about what this refactor does and what issue it solves? I'd love to see a failing test that this PR solves.

**Comment by Simon-He95** [comment]
> Thanks! Can you clarify a bit about what this refactor does and what issue it solves? I'd love to see a failing test that this PR solves.

It can bring some performance improvements because you will skip unnecessary condition judgments. Assuming that you have entered the condition of char == ':', in the original situation, you will still judge it as @ or $.

**Comment by tipiirai** [comment]
Gotcha. Thanks!

**Pull request merged**
