### PR TITLE
fix: email format and send email functioning in Nue FAQ

### PR DESCRIPTION
**Pull request by kappalasaimohith**
Fixed email display in FAQ to ensure it shows correctly and is clickable.

### CODE REVIEW

**Comment by kappalasaimohith** [comment]
Fixed email display in FAQ to ensure it shows correctly and is clickable.

**Comment by nobkd** [comment]
I think this was intentional, so bots don't scrape it as easily.
@tipiirai can probably tell you better than me, because it's just an assumption on my end :)

**Comment by tipiirai** [comment]
Yes. This was intentional. Not sure if this a valid trick anymore. I bet that today's bots can scrape that. What do you think?

**Comment by kappalasaimohith** [comment]
@tipiirai and @nobkd  Thanks for the clarification! I understand it was intentional, and I agree it may not hold up against modern bots.

**Pull request closed without merging**
